# Definiert das AddOn, grundlegende Einstellungen - Diese Detei ist unbedingt erforderlich
# Dokumentation der `package.yml` https://redaxo.org/doku/master/addon-package
# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: ff_copy_tool # Pflichtfeld
version: "1.0.1" # Pflichtfeld
author: Oliver Hörold # Pflichtfeld für FOR-AddOns
supportpage: https://github.com/omphteliba/ff_copy_tool # Github-Adresse des AddOns

# Werte die mit `translate:` beginnen, werden anhand der Sprachdatei (lang/sprache.lang) übersetzt.
# Der AddOn-Präfix (hier `ff_copy_tool_`) kann weggelassen werden.

# Seiten des AddOns
page:
  title: "translate:navititle" # Bezeichnung in der REDAXO Navigation
  icon: rex-icon fa-desktop # Icon von Font Awesome
  perm: ff_copy_tool[]
  pjax: true # Hier kann die Verwendung von PJAX für das eigene AddOn gesteuert werden
  # mit der Einstellung `prio` kann die Position im Hauptmenü beeinflusst werden
  #prio: 10

  # Unterseiten
  subpages:
    copy:
      title: 'translate:copy'
      perm: ff_copy_tool[]
    config:
      title: 'translate:config'
      perm: ff_copy_tool[config]  # config-Seite mit separaten Rechten
    info:
      title: 'translate:info'
      itemclass: 'pull-right'
      subpages:
        info: { title: 'translate:info' }
        changelog: { title: 'translate:changelog' }
        lizenz: { title: 'translate:lizenz' }'
# Abhängigkeiten
# Anforderungen ans System oder anderere AddOns, um dieses AddOn installieren oder updaten zu können
requires:
  redaxo: "^5.10" # benötigt mindestens REDAXO 5.10
  packages:
    yform: ">3.4.0"
  plugins:
    yform/rest: ">3.4.0"
  php:
    version: ">=8" # benötigt mindestens PHP 8

# Plugins die automatisch installiert werden sollen
system_plugins:

# Installer (ab REX 5.7)
# Angabe von Ordnern und Dateien, die vom Installer ausgelassen werden sollen, wenn ein Release veröffentlicht wird
# Siehe auch https://github.com/redaxo/redaxo/pull/2352
installer_ignore:
  - .env

